# both generic "make" and "make strassen" using
# single dependency of strassen.cpp
problem5.1: problem5.1.cpp
	 g++ -o problem5.1 problem5.1.cpp
     

# removes the executable
clean:
	 rm problem5.1